### ISSUE TITLE
notes from pilot session

### ISSUE THREAD

**Issue by nehamoopen** [UtrechtUniversity/workshop-introduction-to-python#60]
- [x] downloading and extracting the materials could be made more explicit with an expected directory tree, because now we download a zip file called course_materials which is extracted into a folder called course_materials and participants are liable to move this folder into the intro-python folder on their Desktop, resulting in something like: ~/Desktop/intro-python/course_materials/data etc. when we really want ~/Desktop/intro-python/data..

- [x]  we ask people to start the jupyter notebook in the data folder, but we should ask them to do that in the intro-python folder

- [x] i think we just started with anaconda and jupyter and immediately got into the first module? it would be good to take a moment to go over the schedule and let participants know what to expect and then explicitly state we are going to cover so-and-so module now

- [x] we should also take a little more time to distinguish between the book and exercises notebook and the empty notebook etc. what is the purpose of each etc. Maybe we just give them a playground notebook as well, in addition to the exercises notebook? I was confused for a while until i realized I should code along.

- [x] make the exercise numbers more bold or something

- [x] perhaps we should take some time for people to finish the exercises, but also go over the exercises and explain them?

**Comment by nehamoopen** [comment]
- do we want the exercise code + solutions in the book itself somehow? perhaps hidden under a drop-down menu of sorts?

**Comment by RoelBrouwer** [comment]
- Some lists do not render with line breaks (in 2.1 for example)

**Comment by nehamoopen** [comment]
- for exercise 0 = maybe a new cell to type in the adapted code, rather than edit the first cell?

**Comment by jelletreep** [comment]
Exercise 0 should be moved to the end of chapter 3 (so all exercises 0-3) and we should clearly explain string concatenation

**Comment by nehamoopen** [comment]
it would also be good to ensure impatient students like me and Dorien don't (often) end up not listening to the demo and trying only the exercises and then maybe ending up with questions 😅

**Comment by RoelBrouwer** [comment]
Chapter 4:
- Add some more on dictionary keys being unique (but overwriteable)
- Add explanation on dict_keys, dict_values being list-like objects, but not true lists

**Comment by nehamoopen** [comment]
- in general for the exercises, it might to be nice to provide some hints for where exactly (like subsections) to refer in the book for help? i don't know if it's possible, have to revisit the layout..no harm in actually asking questions either

**Comment by RoelBrouwer** [comment]
Looking at the contents of the book now, I see that Stefano improvised a large part of the content (he did end up at the fahr_to_celsius example), but before that it was significantly different. We need to discuss whether to change the chapter to match this, or change the teaching to match the chapter more closely.
In my opinion, we do not need to match the book exactly when teaching, but at least follow the general line, so people can refer back and recognize what was taught.

**Comment by RoelBrouwer** [comment]
- I think we should avoid using list comprehensions and other concepts that we in general do not want to teach in this course.

**Comment by DorienHuijser** [comment]
My notes from the morning session:


- Installation & set-up: 
  - I already had Anaconda installed. 
    - How do I check if I have the correct Python version?
    - How do I check if Python is in the PATH variable?
  - Creating a new notebook:
    - Should be created in the root folder, not in `data` (bad practice)
    - first step should be to give the notebook a filename
  - what are we supposed to do with the notebook? If someone is unfamiliar with how notebooks work, they may deserve some introduction before diving into the content > ah Neha mentioned this will be in the introduction page nvm
- Variables and printing output:
  - The bulleted list "In Python, variable names:..." is not displayed as a list
- Operators and built-in functions:
  - "We typically provide a function with ‘arguments’ to tell python which values or variables are used to perform the body of the function." suggestion to rewrite as "Arguments are used by a function to perform the function and, if relevant, return results."
- Data types: can we add an extra header for tuples? Otherwise the text is so long
- Morning exercises
  - Exercise 0, question 2: I interpreted the question "the variable names and values are printed as output" as `print(x)`, `print(apple)`, `print('x')`, and `print('apple')`
  - Exercise 1 typo: "1. Calculate: One plus five divided by nine amd assign the result of the calculation to a variable." --> amd = and
  - Exercise 3 does not contain the answers/solutions
  - Exercise 5 question 2: the solution returns the elements from the `age` list instead of the `name` list
  - Exercise 5 question 3: the solution looks a bit different than expected. The exercise does not specify to create a new variable new_age. My solution was much simpler: `for a in age: if a < 30: print(a)`
  - Exercise 8: maybe mention in the instructions what the function name should be

**Comment by RoelBrouwer** [comment]
Usefull to remember for when anyone (used to Rstudio) asks about the variables that have been defined in the 'environment':
Python has the `locals()` function, which shows you a dictionary of _all_ defined variables (also things that you do not really want to see, like `__name__` etc.).
IPython (and thereby Jupyter Notebooks as well) provide some magic commands:
`%who` gives you the names of all user-defined variables
`%whos` gives you a table of user-defined variables, like so:
```
Variable   Type    Data/Info
----------------------------
a          int     1
b          str     w
```

**Comment by nehamoopen** [comment]
In the exercises for the afternoon (at least 3, 4, 5) - it might be nice to provide empty cells for each line of code we're supposed to run. In the R course, I sometimes see participants doing a bunch of things within one knitr code chunk and it gets very messy

**Comment by nehamoopen** [comment]
> Looking at the contents of the book now, I see that Stefano improvised a large part of the content (he did end up at the fahr_to_celsius example), but before that it was significantly different. We need to discuss whether to change the chapter to match this, or change the teaching to match the chapter more closely. In my opinion, we do not need to match the book exactly when teaching, but at least follow the general line, so people can refer back and recognize what was taught.

Some flexibility is fine, but keeping to the general line is also useful for whoever will end up teaching the course - instructors who take turns don't have to improvise too much or overprepare every time but they can use the book and its examples as a guide.

**Comment by nehamoopen** [comment]
I would perhaps render the jupyter notebook with solutions to HTML with all output, otherwise you have to go through the notebook and run the cells to see what the results should look like and in a busy session with lots of questions - it's easier to just scroll through the solutions and immediately see what the results should look like.

**Comment by maartenschermer** [comment]
# Afternoon session

My remarks for the afternoon session:

## Exercise 1
- [ ] Shouldn't it be 'Exercise 0', just as in the morning session?

## Exercise 2
- [ ] "does the statistics make sense?" --> "do the statistics make sense?"
- [ ] "weight.counts()" --> "weight.count()"

## Exercise 3
- [ ] "How does the results look like and why?" --> "What do the results look like and why?"
- [ ] "occurrs" --> "occurs" (2x)

## Exercise 4
- [ ] The last bit - "What happens when you call: ..." - also appear as Exercise 5.

## Exercise 7
- [ ] "leave out samples we do not know" --> "leave out samples of which we do not know"

## Exercise 9
- [ ] "and why dos it not" --> "and why does it not"

## Exercice 13
- [ ] matplotlib is not being imported (or mentioned before being used; text is about native Pandas DataFrame-plot)

**Comment by jelletreep** [comment]
Everything has been dealt with or moved to another issue
